services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easyodoo-app
    restart: always
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/addons
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - ODOO_CMD_ARGS=${ODOO_CMD_ARGS}
    networks:
      - easyodoo_network
    ports:
      - "${ODOO_PORT:-8069}:8069"  # Odoo web interface
      - "${ODOO_HTTPS_PORT:-8071}:8071"  # Odoo HTTPS interface
      - "${ODOO_LONGPOLL_PORT:-8072}:8072"  # Odoo longpolling interface

  db:
    image: postgres:12
    container_name: easyodoo-db
    restart: always
    environment:
      - POSTGRES_DB=odoodb
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=easyodoo
    networks:
      - easyodoo_network

networks:
  easyodoo_network:
    driver: bridge
